# Generated by Django 2.2.6 on 2019-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptnum', models.CharField(max_length=120)),
                ('claimnum', models.CharField(max_length=120)),
                ('apptDate', models.DateField()),
                ('apptTime', models.DateTimeField()),
                ('apptType', models.CharField(max_length=120)),
                ('hcname', models.CharField(max_length=120)),
                ('apptadd', models.TextField(blank=True, null=True)),
                ('startadd', models.TextField(blank=True, null=True)),
                ('nextadd', models.TextField(blank=True, null=True)),
                ('group', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('firstappt', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=False)),
                ('interpreter', models.CharField(max_length=120)),
            ],
        ),
    ]
