# Generated by Django 2.2.6 on 2019-11-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apptDate',
            new_name='apptdate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='apptTime',
            new_name='appttime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='apptType',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appttype',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='claimnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='firstappt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hcname',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='interpreter',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
