# Generated by Django 2.2.6 on 2019-11-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20191108_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lastappt',
            field=models.BooleanField(default=False),
        ),
    ]
