# Generated by Django 2.2.6 on 2019-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_lastappt'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsontest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appttime',
            field=models.TimeField(),
        ),
    ]
