# Generated by Django 2.2.6 on 2019-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20191109_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apptend',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appttype',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='firstappt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hcname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='interpreter',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lastappt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
