# Generated by Django 2.2.6 on 2019-11-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20191118_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='apptnum',
        ),
    ]
