# Generated by Django 2.2.6 on 2019-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_apptnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='endampm',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endhour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startampm',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='starthour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startmin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
