# Generated by Django 2.2.6 on 2019-11-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20191120_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apptend',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appttime',
            new_name='starttime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='endampm',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='endhour',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='endmin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='startampm',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='starthour',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='startmin',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='group',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
