# Generated by Django 2.2.6 on 2019-11-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20191122_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='firstappt',
            new_name='firstlastappt',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lastappt',
        ),
        migrations.AddField(
            model_name='appointment',
            name='endampm',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endhour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endmin',
            field=models.IntegerField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startampm',
            field=models.CharField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='starthour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apptadd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apptdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nextadd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startadd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
