# Generated by Django 2.2.6 on 2019-12-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20191123_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='starttime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='agency',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endampm',
            field=models.CharField(blank=True, choices=[('am', 'AM'), ('pm', 'PM')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptadd', models.CharField(blank=True, max_length=200, null=True)),
                ('startadd', models.CharField(blank=True, max_length=200, null=True)),
                ('nextadd', models.CharField(blank=True, max_length=200, null=True)),
                ('apptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
            ],
        ),
    ]
