# Generated by Django 2.2.6 on 2019-11-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('claimnum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phonenum', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=120)),
                ('doj', models.DateField()),
                ('agency', models.CharField(max_length=120)),
                ('doctors', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
