# Generated by Django 2.2.6 on 2019-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
