# Generated by Django 2.2.6 on 2019-11-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='employer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='employernum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='managerphone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='agency',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='language',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
