# Generated by Django 2.2.6 on 2019-12-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20191109_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='interpreter',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
